name: getcdr3
description: Run in-house python script to collect the CDR3 sequences only
  from the full amino acid sequence, using the context of the CDR3 which
  begins with amino acids which commence after a YYC and terminates with
  the amino acids which precede a WGQ. We also compute the length distribution of
  these CDR3 sequences.
  Note that this approach is not robust to amino acid sequences which do not follow
  this pattern, or contain the motifs in other positions.
keywords:
  - seqretrieval
  - translation
  - genomics
tools:
  - getCDR3.py:
      description: |
        see above
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - translated:
      type: file
      description: |
        FASTA file of aminoacid sequences as translated by in-house script and
        clustered by CD-HIT
      pattern: "*.{fasta,fa}"
output:
  - fasta:
      type: file
      description: FASTA file containing unique CDR3 sequences
      pattern: "*_cdr3.fasta"
  - hist:
      type: file
      description: Histogram of CDR3 lengths
      pattern: "*_cdr3.hist"
  - tsv:
      type: file
      description: TSV file containing all sequences and their CDR3 status
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@davidebag"
  - "@lescai"
maintainers:
  - "@davidebag"
  - "@lescai"
