lint:
nf_core_version: 3.4.1
bump_version:
org_path:
repository_type: pipeline
template:
  author: Davide Bagordo
  description: pipeline to characterise the repertoire of nanobodies
  force: false
  is_nfcore: true
  name: nanorepertoire
  org: nf-core
  outdir: .
  version: 1.0.0
update:
