name: report

channels:
  - conda-forge
  - bioconda
  - defaults
  - r

dependencies:
  - bioconductor-biostrings
  - bioconductor-genomicfeatures
  - bioconductor-gviz
  - bioconductor-rtracklayer
  - bioconductor-variantannotation
  - pandoc
  - r-ape
  - r-knitr
  - r-quarto
  - r-tidyverse
  - r-kableextra
  - bioconductor-biostrings
  - bioconductor-ggtree
  # - bioconductor-msa  # Not available on osx-arm64
  - r-plotly
  - r-seqinr
  - r-base
