---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "report"
description: Generates a final HTML report and summary tables for the analysis
keywords:
  - report
  - visualization
  - genomics
tools:
  - "report":
      description: "R script for generating analysis reports"
      homepage: "https://www.r-project.org/"
      documentation: "https://cran.r-project.org/"
      licence: ["GPL-3.0-or-later"]

input:
  - report:
      type: file
      description: RMarkdown/Quarto report template
      pattern: "*.{Rmd,qmd}"
  - loop_tree:
      type: file
      description: Loop tree file
      pattern: "*.{Rmd,qmd}"
  - clustersummaries:
      type: file
      description: List of cluster summary files
      pattern: "*.summary"
  - cdr3histograms:
      type: file
      description: List of CDR3 histogram files
      pattern: "*.hist"
  - cdr3tables:
      type: file
      description: List of CDR3 table files
      pattern: "*.tsv"
  - metadata:
      type: file
      description: Metadata file
      pattern: "*.{csv,tsv}"

output:
  - rdata:
      type: file
      description: RData file containing the analysis environment
      pattern: "*.RData"
  - report:
      type: file
      description: Final HTML report
      pattern: "*.html"
  - results:
      type: file
      description: CDR3 boost overview table
      pattern: "cdr3_boost_overview_table.tsv"
  - sampledata:
      type: file
      description: Sample data table
      pattern: "sampledata.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@davidebag"
  - "@lescai"
maintainers:
  - "@davidebag"
  - "@lescai"
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@DavideBag"
maintainers:
  - "@DavideBag"
