name: nf-core AWS full size tests
<<<<<<< HEAD
# This workflow is triggered on PRs opened against the master branch.
=======
# This workflow is triggered on PRs opened against the main/master branch.
>>>>>>> TEMPLATE
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
<<<<<<< HEAD
  pull_request:
    branches:
      - master
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
=======
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  release:
    types: [published]
>>>>>>> TEMPLATE

jobs:
  run-platform:
    name: Run AWS full tests
<<<<<<< HEAD
    # run only if the PR is approved by at least 2 reviewers and against the master branch or manually triggered
    if: github.repository == 'nf-core/nanorepertoire' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: check_approvals
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: test_variables
        if: github.event_name != 'workflow_dispatch'
        run: |
          JSON_RESPONSE='${{ steps.check_approvals.outputs.data }}'
          CURRENT_APPROVALS_COUNT=$(echo $JSON_RESPONSE | jq -c '[.[] | select(.state | contains("APPROVED")) ] | length')
          test $CURRENT_APPROVALS_COUNT -ge 2 || exit 1 # At least 2 approvals are required
=======
    # run only if the PR is approved by at least 2 reviewers and against the master/main branch or manually triggered
    if: github.repository == 'nf-core/nanorepertoire' && github.event.review.state == 'approved' && (github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'main') || github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Set revision variable
        id: revision
        run: |
          echo "revision=${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'release') && github.sha || 'dev' }}" >> "$GITHUB_OUTPUT"

>>>>>>> TEMPLATE
      - name: Launch workflow via Seqera Platform
        uses: seqeralabs/action-tower-launch@v2
        # TODO nf-core: You can customise AWS full pipeline tests as required
        # Add full size test data (but still relatively small datasets for few samples)
        # on the `test_full.config` test runs with only one set of parameters
        with:
          workspace_id: ${{ vars.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ vars.TOWER_COMPUTE_ENV }}
          revision: ${{ steps.revision.outputs.revision }}
          workdir: s3://${{ vars.AWS_S3_BUCKET }}/work/nanorepertoire/work-${{ steps.revision.outputs.revision }}
          parameters: |
            {
              "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
              "outdir": "s3://${{ vars.AWS_S3_BUCKET }}/nanorepertoire/results-${{ steps.revision.outputs.revision }}"
            }
          profiles: test_full

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: Seqera Platform debug log file
          path: |
            tower_action_*.log
            tower_action_*.json
